workflows:
  android-workflow:
    name: Android Kotlin Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    environment:        
      java: 17
      
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'main'
          include: true
          source: true
      
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Get dependencies
        script: |
          cd $CM_BUILD_DIR
          ./gradlew dependencies
          
      - name: Build Android APK
        script: |
          cd $CM_BUILD_DIR
          ./gradlew assembleRelease
          
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
      
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
          
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true